version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - laravel-blog-network
    volumes:
      - db_data_test:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: laravel_redis
    restart: unless-stopped
    networks:
      - laravel-blog-network
    ports:
      - "${REDIS_PORT}:6379"
volumes:
  db_data_test:
    driver: local

networks:
  laravel-blog-network:
    driver: bridge
