version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    networks:
      - blog-network
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - blog-network
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: laravel_redis
    restart: unless-stopped
    networks:
      - blog-network
    ports:
      - "${REDIS_PORT}:6379"
volumes:
  db_data:
    driver: local

networks:
  blog-network:
    driver: bridge
